import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout 是 Next.js 应用的根布局组件
// 它包装了应用中的所有页面组件
export default function RootLayout({
  children,  // children 参数接收子组件
}: Readonly<{  // 使用 Readonly 确保 props 类型不可变
  children: React.ReactNode;  // 定义 children 的类型为 React 节点
}>) {
  return (
    // 定义基本的 HTML 结构
    <html lang="en">  {/* 设置语言为英文 */}
      <body className="bg-white">  {/* 应用 Inter 字体 */}
        <h1>我是Root Layout</h1>
        {children}  {/* 渲染传入的子组件 */}
      </body>
    </html>
  );
}
