import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout 是 Next.js 应用的根布局组件
// 它包装了应用中的所有页面组件
export default function RootLayout({
  children,  // children 参数接收子组件
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  {/* 设置语言为英文 */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
