import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout 是 Next.js 应用的根布局组件
// 它包装了应用中的所有页面组件
export default function RootLayout({
  children,  // children 参数接收子组件
}: Readonly<{  // 使用 Readonly 确保 props 类型不可变
  children: React.ReactNode;  // 定义 children 的类型为 React 节点
}>) {
  return (
    <div>
      <h1>这里是blog layout 博客布局</h1>
      {children}
    </div>
  );
}
